name: Testing API  
on: [push, pull_request]  
jobs:  
  testing-api:  
    runs-on: ubuntu-latest  
    env:  
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}  
    steps:  
      - name: Checkout the repo  
        uses: actions/checkout@v2  
      - name: Creating and activating virtualenv  
        run: |  
          pip3 install virtualenv  
          virtualenv venv  
          source venv/bin/activate  
      - name: Installing dependencies  
        run: |  
          pip install dvc[azure]  
          pip install -r requirements_test.txt  
      - name: Test API  
        run: |  
          export AZURE_STORAGE_CONNECTION_STRING=$(python utilities/setter.py)  
          dvc pull model/model.pkl
          pytest tests.py
